version: '3'

services:
  simwire-flask-ecs:
    build: ./simwire-backend
    image: simwire-flask-ecs:latest
    container_name: simwire-flask-ecs
    network_mode: host

  simwire-flask-ecs-nginx:
    build: ./nginx
    image: simwire-flask-ecs-nginx:latest
    container_name: simwire-flask-ecs-nginx
    network_mode: host
    depends_on:
      - simwire-flask-ecs